<?php

namespace Tests\Unit;

use App\User;
use Tests\TestCase;
use Illuminate\Foundation\Testing\WithFaker;
use Illuminate\Foundation\Testing\RefreshDatabase;

class UsersTest extends TestCase
{
    use RefreshDatabase;
    /**
     * A basic test example.
     *
     * @return void
     */
    protected function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->seed();
    }

    public function testCreateUser()
    {
        $user = [
            'name' => 'Test user',
            'email' => 'qwerty@qwerty.ru'
        ];
        $password = [
            'password' => 'qwerty',
            'password_confirmation' => 'qwerty'
        ];
        $response = $this->post('/register', array_merge($user, $password));

        $response->assertRedirect('/home');

        $this->assertDatabaseHas('users', $user);
    }

    public function testProfileUser() {
        $response = $this->post('/login', [
            'email' => 'user@user.com',
            'password' => 'password',
            'remember' => true
        ]);

        $response->assertRedirect('/home');

        $response->assertStatus(302);

        $profile = $this->get(route('users.profile'));

        $this->post(route('users.save.profile'), [
            'name' => 'Qwerty'
        ]);

        $this->assertDatabaseHas('users', [
            'email' => 'user@user.com',
            'name' => 'Qwerty',
            'api_token' => null
        ]);

        $this->get(route('users.token'));
    }


}
